name: ROS CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [humble, jazzy, kilted]
        arch: [x86_64, arm64]
        exclude:
          - ros_distro: humble
            arch: arm64
          - ros_distro: jazzy
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for ARM64
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: matrix.arch == 'arm64'
        uses: docker/setup-buildx-action@v3

      - name: Build ROS 2 ${{ matrix.ros_distro }} container
        run: |
          docker build \
            --platform linux/${{ matrix.arch }} \
            --build-arg ROS_DISTRO=${{ matrix.ros_distro }} \
            -t ros-ci:${{ matrix.ros_distro }}-${{ matrix.arch }} \
            -f .github/docker/Dockerfile .

      - name: Run build in container
        run: |
          docker run --rm \
            --platform linux/${{ matrix.arch }} \
            -v ${{ github.workspace }}:/workspace \
            ros-ci:${{ matrix.ros_distro }}-${{ matrix.arch }} \
            /bin/bash -c "cd /workspace && colcon build --symlink-install --event-handlers console_direct+"
